MODEL:
  NUM_CLASSES: 11 # needs an extra one for background

INPUT:
  IMAGE_SIZE: 320

SOLVER:
  MAX_ITER: 180000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 8
  LR: 1e-3

OUTPUT_DIR: 'outputs/bdd100k_daytime_320_v2'